### ISSUE TITLE
Приоритет операторов в проверке флага FL_LA

### ISSUE THREAD

**Issue by mishka251** [X-Ray-Engine-STALKER/stkutils#1]
В файле `file/entity.pm` часто встречается условие 

```perl
($_[0]->{flags} & stkutils::file::entity::FL_LA == stkutils::file::entity::FL_LA)
```

Если я правильно понимаю - это ошибка и должно быть

```perl
(($_[0]->{flags} & stkutils::file::entity::FL_LA) == stkutils::file::entity::FL_LA)
```
т.к. если я правильно понимаю это проверка на то, установлен ли флаг FL_LA, но условие это не проверяет, т.к. проверка `stkutils::file::entity::FL_LA == stkutils::file::entity::FL_LA` выполняется до оператора `&`

**Comment by PavelBlend** [comment]
@mishka251 я в этом коде не разбираюсь. Залил себе для истории и чтобы не потерять (как обычно бывает). Лучше прислать правки автору на amk. Я не буду принимать pull request'ы и вносить свои правки, так как их лучше вносить в первоисточнике.

**Comment by mishka251** [comment]
@PavelBlend  Спасибо за ответ
